beacon_imp_exp$pcc= ifelse(beacon_imp_exp$risk10a> 0.69, 1, 0)
crosstab(beacon_imp_exp$cc2, beacon_imp_exp$pcc, prop.r= TRUE, plot= FALSE)
beacon_imp_exp$pcc= ifelse(beacon_imp_exp$risk10a> 1.19, 1, 0)
crosstab(beacon_imp_exp$cc2, beacon_imp_exp$pcc, prop.r= TRUE, plot= FALSE)
beacon_imp_exp$pcc= ifelse(beacon_imp_exp$risk10a> 4., 1, 0)
crosstab(beacon_imp_exp$cc2, beacon_imp_exp$pcc, prop.r= TRUE, plot= FALSE)
beacon_imp_exp$pcc= ifelse(beacon_imp_exp$risk10a> 6., 1, 0)
crosstab(beacon_imp_exp$cc2, beacon_imp_exp$pcc, prop.r= TRUE, plot= FALSE)
beacon_imp_exp$pcc= ifelse(beacon_imp_exp$risk10a> 8., 1, 0)
crosstab(beacon_imp_exp$cc2, beacon_imp_exp$pcc, prop.r= TRUE, plot= FALSE)
